### ISSUE TITLE
Implement Teo's hands

### ISSUE THREAD

**Issue by elisabeth-ms** [roboticslab-uc3m/teo-gazebo-models#3]
Add to the Gazebo model fully actuated hands.

**Comment by elisabeth-ms** [comment]
I have included fully actuated hands in the gazebo model. Here there's a video where the joints of each finger are commanded independently.

https://user-images.githubusercontent.com/25179082/129230432-1584d462-58e8-46eb-8f88-69f84cc433cd.mp4

I have also tested the controlboard [RealToSimControlboard](https://github.com/roboticslab-uc3m/tools/tree/master/libraries/YarpPlugins/RealToSimControlboard) that emulates the real lacqueyFetch. 

https://user-images.githubusercontent.com/25179082/129230620-49ae78f3-45a2-4a14-91dd-051dad5436b7.mp4

**Comment by elisabeth-ms** [comment]
I have been testing to grasp an object with Teo's right hand in Gazebo, but the object slipped from the gripper fingers when grasping. In  order to solve this problem, I have included contact and friction parameters in the sdf file of lacquey fetch. Now, I'm able to grasp an object in Gazebo (see video).
 
https://user-images.githubusercontent.com/25179082/129555199-e364f919-e587-4547-b870-107c857befe8.mp4

**Comment by jgvictores** [comment]
Very cool! @elisabeth-ms could you please Pull Request (PR) or simply merge?

**Comment by jgvictores** [comment]
Done via https://github.com/roboticslab-uc3m/teo-gazebo-models/pull/4
